dsheeler/CoverflowAltTab

CoverflowAltTab@dmo60.de/keybinder.js, CoverflowAltTab@dmo60.de/metadata.json
`KeyBindingMode` was renamed to `ActionMode` in 3.16 and this breaks compatibility with previous versions, so new branch will have to be created for 3.14 too.
=> Update for 3.16

CoverflowAltTab@dmo60.de/metadata.json
Despite some errors reported in #45, adding the recently released version to the metadata.json makes it work just fine on my Arch Linux installation, so you may consider this simple update while working out further hiccups.
=> declare compatible to shell version 3.18

README.markdown
Explain in README that AlternateTab and similar extensions must be disabled for CoverflowAltTab to work
=> Add Troubleshooting section to README

CoverflowAltTab@dmo60.de/metadata.json
[Gnome 3.20 was released](https://www.gnome.org/news/2016/03/gnome-3-20-released/) yesterday.
I just tested and this extension works fine under Gnome 3.20!
=> Support for Gnome 3.20

CoverflowAltTab@dmo60.de/switcher.js
When the Dash to Dock is always visible it appears in Coverflow. But when the option to "hide-panel" is active, is preferred to hide the Dash to Dock.
When you hide the Dash to Dock is necessary to hide the Legacy Tray too, or it will appear in the middle of Coverflow.
This commit hides the Dash to Dock and the Legacy Tray in the Coverflow.
=> Gnome-Shell: Hide dash(e.g. Dash to Dock) and Legacy Tray in the Coverflow

CoverflowAltTab@dmo60.de/metadata.json, CoverflowAltTab@palatis.blogspot.com/metadata.json
As already mentioned in #95, Coverflow should work with the recent gnome-shell version. As the maintainer of a package for this extension in the [Arch Linux User Repository](https://aur.archlinux.org/packages/gnome-shell-extension-coverflow-alt-tab/), I tried it out on a current install. As far as I can tell, everything seems to work just fine, although I could not yet test multi-monitor support.
I propose also tagging a new release after the merge of this request so that the change propagates to all users of the packaged version.
=> Declare compatible to gnome-shell version 3.32

CoverflowAltTab@dmo60.de/coverflowSwitcher.js, CoverflowAltTab@dmo60.de/timelineSwitcher.js
This probably requires some testing.
----
MetaShapedTexture is now a subclass of Clutter.Content and thus is no longer an actor. Also, get_size() function is now gone so use get_preferred_size() (which returns a boolean and two ints).
Fixes #106 on my machine (Arch Linux, GNOME & Mutter 3.34 with some performance patches)
=> Fix compatibility with GNOME3.34

CoverflowAltTab@dmo60.de/switcher.js
As with the previous PR, please check whether the commit suppresses all of the `Usage of object.actor is deprecated for Panel` (example message in #108).
=> Replace panel.actor calls to silence the deprecation notices

makefile
I have a non-default path to my home directory, i.e., something other than /home/username, so installing into my home directory didn't work.  So instead of constructing the path out of /home/ + username, I get the path from the $HOME environment variable.  Also added an uninstall option.
=> Use $HOME env variable in makefile; add uninstall

CoverflowAltTab@dmo60.de/coverflowSwitcher.js, CoverflowAltTab@dmo60.de/switcher.js
While this didn't break my 3.36 install, I can't verify it works on 3.34 (where Graphene wasn't a dependency of Mutter), which is the version affected.
Should fix #123 .
=> Import Graphene only when necessary (shell version >= 3.36)

CoverflowAltTab@dmo60.de/switcher.js
There were two bugs. one where the windows are not drawn exactly how they should after one full rotate of all apps.
and second is closing using f4 shows animation as if two apps are closed.
=> fixed animation error after full rotate of all apps

CONTRIBUTORS.markdown, CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.po
New strings (last update : 7 years ago)
Better consistency regarding GNOME guidelines (use ’ of instead of ') and GNOME mutter translation.
Better internal consistency ("smaller" is "plus petit" + not using "=", "Overlay" is rather not used as a verb in French in this context, etc.)
=> French translation update (new str. + consist. & corr.)

locale/CoverflowAltTab@palatis.blogspot.com.pot, locale/cs.po, locale/de.po, locale/fr.po, locale/it.po, locale/ja.po, locale/nl.po, locale/pt_BR.po, locale/ru.po, locale/sv.po, locale/tr.po, locale/zh_CN.po, locale/zh_TW.po, src/prefs.js
Updated a couple of small spelling mistakes / typos in words in the preferences dialog.
Regenerated translation files.
=> Fix preferences label typos

src/coverflowSwitcher.js, src/swipeTracker.js, src/switcher.js, src/timelineSwitcher.js
Cycle through windows smoothly (instead of in jumps) using the scroll wheel.  This works way better than the old scroll behavior that always skipped at least two windows ahead instead of one. Closes #221
=> Add a mousewheel gesture to swipe tracker and use it!

src/platform.js
Add a name to the background group actor so that other Gnome extensions may utilize the name to find and customize the background effects of the switcher.
Related to https://github.com/aunetx/blur-my-shell/pull/633
=> Add a name to the background group

metadata.json
Adding in 47 to the shell version works in 47.rc from my test's.
=> Add Gnome 47.rc

src/prefs.js
This fixes the warning about invalid values is shown in the journal like this:
```
gjs[12206]: g_settings_set_value: value for key 'switcher-looping-method' in schema 'org.gnome.shell.extensions.coverflowalttab' is outside of valid range
```
=> Fix missing values for some GSettings keys

src/lib.js, src/manager.js, src/platform.js, src/prefs.js, src/switcher.js
- Unify to use spaces indentation instead of a tab
- Add missing space after `if` and the begging parenthesis
- Remove extra tab in the end of the line
=> Use spaces indentation instead of a tab

src/prefs.js
- Create arrays of our own objects instead of Maps for clean data structure
- Have choices in a key of settings in our objects instead of converting label text
- This frees us from updating `getBaseString()` when adding new RadioAdws!
- Prefer readable and meaningful variable names
- Use literal true/false because this case the radio button is current selection
- Do not update sensitivity when the radio button gets deactivated because updating should be performed by the activated radio button
(I'm not familiar with JS so might be misunderstanding your code and making inappropriate changes…)
=> RadioButtons: Refactor and correct setting sensitivity of other widgets 

src/prefs.js
This fixes the following warning is shown in the journal when the preferences dialog gets present.
gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
=> Fix appending widgets to the box twice

src/prefs.js, src/shortcutButton.js
This fixes the "Internal Actions Keybindings" section is not translatable and always shown in English regardless of the system language:
=> Fix missing translatable texts
